language: generic

sudo: required

env:
  global:
    - FONTS_DIR="$TRAVIS_BUILD_DIR/fonts"

services:
  - docker

install:
  - docker pull maximbaz/emojione-fonts-build
  - mkdir "$FONTS_DIR"

script:
  - docker run --rm -v "$FONTS_DIR":/fonts -v "$TRAVIS_BUILD_DIR":/assets maximbaz/emojione-fonts-build

deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "$FONTS_DIR/emojione-android.ttf"
    - "$FONTS_DIR/emojione-android-alt.ttf"
